services:
  ms-customer:
    container_name: ms-customer
    restart: on-failure
    ports:
      - "8080:8080"
    build: ./ms-customer
    environment:
      # Server Configuration
      SERVER_PORT: 8080

      # Spring Application
      SPRING_APPLICATION_NAME: ms-shopping-cart

      # Locale Configuration
      SPRING_WEB_LOCALE_RESOLVER: fixed
      SPRING_WEB_LOCALE: pt-BR

      # Cors Configuration
      SPRING_WEB_CORS_ALLOWED_ORIGINS: "http://localhost:4200"
      SPRING_WEB_CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE"
      SPRING_WEB_CORS_ALLOWED_HEADERS: "Content-Type,Authorization"
      SPRING_WEB_CORS_ALLOW_CREDENTIALS: "true"
      SPRING_WEB_CORS_MAX_AGE: 3600

      #PostgreSQL Database Connection
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.ffszbrjsbhmwfsxoenvt.supabase.co:5432/postgres?user=postgres&password=IjfSFcmjc5XTo3TM
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: IjfSFcmjc5XTo3TM
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # JPA Configuration
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect

      # Springdoc OpenApi & Swagger
      SPRINGDOC_SWAGGER-UI_PATH: /docs.html
      SPRINGDOC_API-DOCS_PATH: /docs
      SPRINGDOC_PACKAGES-TO-SCAN: tg.espetinho.web.controller
    depends_on:
      - ms-order
    networks:
      - backend

  ms-delivery:
    container_name: ms-delivery
    restart: on-failure
    ports:
      - "8081:8081"
    build: ./ms-delivery
    environment:
      # Server Configuration
      SERVER_PORT: 8081

      # Spring Application
      SPRING_APPLICATION_NAME: ms-shopping-cart

      # Locale Configuration
      SPRING_WEB_LOCALE_RESOLVER: fixed
      SPRING_WEB_LOCALE: pt-BR

      # Cors Configuration
      SPRING_WEB_CORS_ALLOWED_ORIGINS: "http://localhost:4200"
      SPRING_WEB_CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE"
      SPRING_WEB_CORS_ALLOWED_HEADERS: "Content-Type,Authorization"
      SPRING_WEB_CORS_ALLOW_CREDENTIALS: "true"
      SPRING_WEB_CORS_MAX_AGE: 3600

      #PostgreSQL Database Connection
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.ffszbrjsbhmwfsxoenvt.supabase.co:5432/postgres?user=postgres&password=IjfSFcmjc5XTo3TM
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: IjfSFcmjc5XTo3TM
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # JPA Configuration
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect

      # Springdoc OpenApi & Swagger
      SPRINGDOC_SWAGGER-UI_PATH: /docs.html
      SPRINGDOC_API-DOCS_PATH: /docs
      SPRINGDOC_PACKAGES-TO-SCAN: tg.espetinho.web.controller
    networks:
      - backend

  ms-order:
    container_name: ms-order
    restart: on-failure
    ports:
      - "8082:8082"
    build: ./ms-order
    environment:
      # Server Configuration
      SERVER_PORT: 8082

      # Spring Application
      SPRING_APPLICATION_NAME: ms-shopping-cart

      # Locale Configuration
      SPRING_WEB_LOCALE_RESOLVER: fixed
      SPRING_WEB_LOCALE: pt-BR

      # Cors Configuration
      SPRING_WEB_CORS_ALLOWED_ORIGINS: "http://localhost:4200"
      SPRING_WEB_CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE"
      SPRING_WEB_CORS_ALLOWED_HEADERS: "Content-Type,Authorization"
      SPRING_WEB_CORS_ALLOW_CREDENTIALS: "true"
      SPRING_WEB_CORS_MAX_AGE: 3600

      #PostgreSQL Database Connection
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.ffszbrjsbhmwfsxoenvt.supabase.co:5432/postgres?user=postgres&password=IjfSFcmjc5XTo3TM
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: IjfSFcmjc5XTo3TM
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # JPA Configuration
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect

      # Springdoc OpenApi & Swagger
      SPRINGDOC_SWAGGER-UI_PATH: /docs.html
      SPRINGDOC_API-DOCS_PATH: /docs
      SPRINGDOC_PACKAGES-TO-SCAN: tg.espetinho.web.controller
    depends_on:
      - ms-shopping-cart
      - ms-delivery
    networks:
      - backend

  ms-product:
    container_name: ms-product
    restart: on-failure
    ports:
      - "8083:8083"
    build: ./ms-product
    environment:
      # Server Configuration
      SERVER_PORT: 8083

      # Spring Application
      SPRING_APPLICATION_NAME: ms-shopping-cart

      # Locale Configuration
      SPRING_WEB_LOCALE_RESOLVER: fixed
      SPRING_WEB_LOCALE: pt-BR

      # Cors Configuration
      SPRING_WEB_CORS_ALLOWED_ORIGINS: "http://localhost:4200"
      SPRING_WEB_CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE"
      SPRING_WEB_CORS_ALLOWED_HEADERS: "Content-Type,Authorization"
      SPRING_WEB_CORS_ALLOW_CREDENTIALS: "true"
      SPRING_WEB_CORS_MAX_AGE: 3600

      #PostgreSQL Database Connection
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.ffszbrjsbhmwfsxoenvt.supabase.co:5432/postgres?user=postgres&password=IjfSFcmjc5XTo3TM
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: IjfSFcmjc5XTo3TM
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # JPA Configuration
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect

      # Springdoc OpenApi & Swagger
      SPRINGDOC_SWAGGER-UI_PATH: /docs.html
      SPRINGDOC_API-DOCS_PATH: /docs
      SPRINGDOC_PACKAGES-TO-SCAN: tg.espetinho.web.controller
    networks:
      - backend

  ms-shopping-cart:
    container_name: ms-shopping-cart
    restart: on-failure
    ports:
      - "8084:8084"
    build: ./ms-shopping-cart
    environment:
      # Server Configuration
      SERVER_PORT: 8084

      # Spring Application
      SPRING_APPLICATION_NAME: ms-shopping-cart

      # Locale Configuration
      SPRING_WEB_LOCALE_RESOLVER: fixed
      SPRING_WEB_LOCALE: pt-BR

      # Cors Configuration
      SPRING_WEB_CORS_ALLOWED_ORIGINS: "http://localhost:4200"
      SPRING_WEB_CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE"
      SPRING_WEB_CORS_ALLOWED_HEADERS: "Content-Type,Authorization"
      SPRING_WEB_CORS_ALLOW_CREDENTIALS: "true"
      SPRING_WEB_CORS_MAX_AGE: 3600

      #PostgreSQL Database Connection
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.ffszbrjsbhmwfsxoenvt.supabase.co:5432/postgres?user=postgres&password=IjfSFcmjc5XTo3TM
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: IjfSFcmjc5XTo3TM
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # JPA Configuration
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect

      # Springdoc OpenApi & Swagger
      SPRINGDOC_SWAGGER-UI_PATH: /docs.html
      SPRINGDOC_API-DOCS_PATH: /docs
      SPRINGDOC_PACKAGES-TO-SCAN: tg.espetinho.web.controller
    depends_on:
      - ms-product
    networks:
      - backend

networks:
  backend:
    driver: bridge