version: '3.8'

services:
  ms-customer:
    image: cassiocintra/${PROFILE}-ms-customer:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}

  ms-delivery:
    image: cassiocintra/${PROFILE}-ms-delivery:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}

  ms-order:
    image: cassiocintra/${PROFILE}-ms-order:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}

  ms-product:
    image: cassiocintra/${PROFILE}-ms-product:latest
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}

  ms-shopping-cart:
    image: cassiocintra/${PROFILE}-ms-shopping-cart:latest
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}