# Install Maven
FROM openjdk:21-jdk-slim AS build
RUN apt-get update && apt-get install -y maven

# Build
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean package

# Runtime
FROM openjdk:21-jdk-slim
ARG JAR_FILE=target/ms-product-0.0.1-SNAPSHOT.jar
COPY --from=build ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]

# Expose Port 8083
EXPOSE 8083