name: Build Microservices

on:
  workflow_call:
    inputs:
      spring_profile:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ms: ['ms-customer', 'ms-delivery', 'ms-order', 'ms-product', 'ms-shopping-cart']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Maven package
        run: |
          cd ${{ matrix.ms }}
          mvn clean install -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug secrets
        run: |
          echo "Username: ${{ secrets.DOCKER_USERNAME }}"
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "DOCKER_USERNAME is empty"; exit 1; fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then echo "DOCKER_PASSWORD is empty"; exit 1; fi
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        id: build
        run: |
          cd ${{ matrix.ms }}
          TAG="${{ inputs.spring_profile }}-$(date +%Y%m%d%H%M%S)"
          docker build -t cassiocintra/tg-backend:$TAG \
            --build-arg SPRING_PROFILES_ACTIVE=${{ inputs.spring_profile }} .
          docker tag cassiocintra/tg-backend:$TAG cassiocintra/tg-backend:${{ inputs.spring_profile }}
          docker push cassiocintra/tg-backend:$TAG
          docker push cassiocintra/tg-backend:${{ inputs.spring_profile }}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Save tag as artifact
        if: github.ref == 'refs/heads/main'  # Apenas em produção
        run: |
          echo "${{ steps.build.outputs.tag }}" > latest-tag.txt
          mkdir -p artifacts
          mv latest-tag.txt artifacts/

      - name: Upload tag artifact
        if: github.ref == 'refs/heads/main'  # Apenas em produção
        uses: actions/upload-artifact@v4
        with:
          name: latest-tag
          path: artifacts/latest-tag.txt