name: Clean Up Docker Hub Tags

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Clean up old Docker Hub tags
        run: |
          USERNAME="${{ secrets.DOCKER_USERNAME }}"
          PASSWORD="${{ secrets.DOCKER_PASSWORD }}"
          PROFILE="${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}"
          MICROSERVICES="ms-customer ms-delivery ms-order ms-product ms-shopping-cart"

          if [ -z "$USERNAME" ] || [ -z "$PASSWORD" ]; then
            echo "Erro: DOCKER_USERNAME ou DOCKER_PASSWORD não estão definidos."
            exit 1
          fi

          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST \
            -d "{\"username\": \"$USERNAME\", \"password\": \"$PASSWORD\"}" \
            https://hub.docker.com/v2/users/login/ | jq -r .token)

          if [ -z "$TOKEN" ]; then
            echo "Erro: Não foi possível obter o token."
            exit 1
          fi

          for MS in $MICROSERVICES; do
            echo "Processando $MS no perfil $PROFILE..."
            IMAGE_NAME="$PROFILE-$MS"
            TAGS=$(curl -s -H "Authorization: JWT $TOKEN" \
              "https://hub.docker.com/v2/repositories/$USERNAME/$IMAGE_NAME/tags/?page_size=100" | \
              jq -r ".results[] | select(.name != \"latest\") | [.name, .last_updated] | join(\" \")")

            mapfile -t SORTED_TAGS < <(echo "$TAGS" | sort -k2 -r)
            TOTAL_TAGS=${#SORTED_TAGS[@]}
            echo "Total de tags (exceto latest) para $MS: $TOTAL_TAGS"

            if [ "$TOTAL_TAGS" -eq 0 ]; then
              echo "Nenhuma tag para limpar (exceto latest) para $MS."
              continue
            fi

            echo "Mantendo a tag mais recente para $MS (além de latest):"
            TAG_NAME=$(echo "${SORTED_TAGS[0]}" | awk '{print $1}')
            echo "- $TAG_NAME"

            echo "Excluindo as tags restantes para $MS:"
            for ((i=1; i<TOTAL_TAGS; i++)); do
              TAG_NAME=$(echo "${SORTED_TAGS[$i]}" | awk '{print $1}')
              echo "Excluindo $TAG_NAME..."
              curl -s -X DELETE -H "Authorization: JWT $TOKEN" \
                "https://hub.docker.com/v2/repositories/$USERNAME/$IMAGE_NAME/tags/$TAG_NAME/"
            done
          done

          echo "Limpeza concluída!"