name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    needs: validate
    uses: ./.github/workflows/build.yml
    with:
      spring_profile: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      spring_profile: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

  deploy:
    needs: test
    uses: ./.github/workflows/deploy.yml
    with:
      spring_profile: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}