name: CI/CD Pipeline
# comentario pro push
on:
  push:
    branches:
      - main
      - dev

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  build:
    needs: validate
    uses: ./.github/workflows/build.yml
    with:
      spring_profile: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      spring_profile: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

  deploy:
    needs: test
    uses: ./.github/workflows/deploy.yml
    with:
      spring_profile: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}