name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  build:
    needs: validate
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    needs: build
    uses: ./.github/workflows/test.yml

  deploy:
    needs: test
    uses: ./.github/workflows/deploy.yml
    secrets: inherit